server:
  port: ${SERVER_PORT:8082}

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:3307}/${DB_NAME:dee-facto}?serverTimezone=UTC&useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
      validation-timeout: 5000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
  # JPA (Java Persistence API) ì„¤ì •
  jpa:
    # Hibernate ì„¤ì •
    hibernate:
      # ë°ì´í„°ë² ì´ìŠ¤ ìŠ¤í‚¤ë§ˆ ìë™ ìƒì„± ì„¤ì • (í™˜ê²½ ë³€ìˆ˜ì—ì„œ ê°€ì ¸ì˜¤ê±°ë‚˜ ê¸°ë³¸ê°’ update ì‚¬ìš©)
      # update: ì—”í‹°í‹° ë³€ê²½ì‚¬í•­ì„ ìë™ìœ¼ë¡œ ë°ì´í„°ë² ì´ìŠ¤ì— ë°˜ì˜
      # create: ì• í”Œë¦¬ì¼€ì´ì…˜ ì‹œì‘ ì‹œ í…Œì´ë¸”ì„ ìƒˆë¡œ ìƒì„± (ê¸°ì¡´ ë°ì´í„° ì‚­ì œ)
      # validate: ì—”í‹°í‹°ì™€ ë°ì´í„°ë² ì´ìŠ¤ ìŠ¤í‚¤ë§ˆ ì¼ì¹˜ ì—¬ë¶€ë§Œ ê²€ì¦
      # none: ìë™ ìŠ¤í‚¤ë§ˆ ìƒì„± ë¹„í™œì„±í™”
      ddl-auto: ${DEV_HIBERNATE_DDL_AUTO:update}

    # SQL ì¿¼ë¦¬ ë¡œê·¸ ì¶œë ¥ ì„¤ì • (í™˜ê²½ ë³€ìˆ˜ì—ì„œ ê°€ì ¸ì˜¤ê±°ë‚˜ ê¸°ë³¸ê°’ true ì‚¬ìš©)
    show-sql: ${DEV_SHOW_SQL:true}

    # Hibernate ì¶”ê°€ ì†ì„± ì„¤ì •
    properties:
      hibernate:
        # SQL ì¿¼ë¦¬ í¬ë§·íŒ… ì„¤ì • (í™˜ê²½ ë³€ìˆ˜ì—ì„œ ê°€ì ¸ì˜¤ê±°ë‚˜ ê¸°ë³¸ê°’ true ì‚¬ìš©)
        # ê°€ë…ì„±ì„ ìœ„í•´ ë“¤ì—¬ì“°ê¸° ì ìš©
        format_sql: ${DEV_FORMAT_SQL:true}

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:StrongPassword22!}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

aws:
  credentials:
    access-key: ${AWS_ACCESS_KEY:test}
    secret-key: ${AWS_SECRET_KEY:test}
  region: ${AWS_REGION:ap-northeast-2}
  sqs:
#  ğŸ”¥ Local SQS ì‚¬ìš© ì‹œ
#    endpoint-url: ${AWS_SQS_ENDPOINT_URL:http://localhost:4566}
    queue-url: ${AWS_SQS_QUEUE_URL:http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/your-queue-name}
